name: Kill mpc-qt
description: "Kill mpc-qt and wait for it to start then check that it's not running"

runs:
  using: "composite"

  steps:
  - name: Wait 15 seconds
    run:  sleep 15
    shell: bash
  - name: Kill mpc-qt
    run:  taskkill /im mpc-qt.exe
    shell: pwsh
  - name: Wait 10 seconds
    run:  sleep 10
    shell: bash
  - name: Check that mpc-qt is not running
    uses: ./.github/actions/windows/commands/check_if_running
    with:
      should_be_running: "no"
