name: Check if running
description: 'Check if mpc-qt is running'

inputs:
  should_be_running:
    description: 'Whether mpc-qt should be running'
    required: true
    default: 'yes'
runs:
  using: "composite"

  steps:
  - name: cat log
    run:  |
      if [ -e mpc-qt.log ]; then
        echo "::group::mpc-qt-running.log"
        cat mpc-qt.log
        echo "::endgroup::"
      fi
    shell: bash
  - name: Check if mpc-qt is running
    run:  |
      : Check if mpc-qt is running
      if [ $( pidof mpc-qt) ]; then
        if [[ "${{ inputs.should_be_running }}" == 'yes' ]]; then
          echo -e "\033[32m""mpc-qt is running ✓""\033[0m"
        else
          echo -e "\033[31m""mpc-qt is running but should not be ✗""\033[0m"
          exit 1
        fi
      elif [[ "${{ inputs.should_be_running }}" == 'no' ]]; then
        echo -e "\033[32m""mpc-qt is not running ✓""\033[0m"
      else
        echo -e "\033[31m""mpc-qt is not running but should be ✗""\033[0m"
        exit 1
      fi
    shell: bash
