name: Run mpc-qt
description: "Run mpc-qt and wait for it to start then check if it's running"

inputs:
  filename:
    description: "File to open with mpc-qt"
    required: false
    default: ""
  locale:
    description: "Locale to use"
    required: false
    default: "en_US.UTF-8"
runs:
  using: "composite"

  steps:
  - name: Run mpc-qt and open a file if provided
    run:  |
        : Set the locale to ${{ inputs.locale }}
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen ${{ inputs.locale }}
        sudo update-locale LANG=${{ inputs.locale }}
        export LANG=${{ inputs.locale }}
        export LANGUAGE=${{ inputs.locale }}
        export LC_ALL=${{ inputs.locale }}
        locale
        : Run mpc-qt
        chmod +x mpc-qt/mpc-qt
        export DISPLAY=:99
        mpc-qt/mpc-qt "${{ inputs.filename }}" &
    shell: bash
  - name: wait 10 seconds
    run:  sleep 10
    shell: bash
  - name: check that mpc-qt is running
    uses: ./.github/actions/linux/commands/check_if_running
    with:
      should_be_running: "yes"
