name: Report a Windows Issue
description: Create a report for an issue on Windows
labels: ["windows"]
type: Bug
body:
- type: textarea
  id: information
  attributes:
      label: Information
      description: >
          If possible, try an [MPC-QT development build](https://mpc-qt.github.io/downloads#dev-builds)
          to make sure the issue hasn't been fixed yet.


          Please provide the following information if applicable, remove unneeded lines:
      value: |
          - MPC-QT version: (shown in the menu Help > About This Program)
          - Windows Version: Windows 10 / Windows 11... (remove non applicable)
          - GPU Make: AMD / Intel / Nvidia (remove non applicable)
          - Latest known working version: 
          - Issue started after the following happened: 
  validations:
      required: true
- type: textarea
  id: description
  attributes:
      label: Description of the issue
      description: |
          Describe your issue here
  validations:
      required: true
