name: Report a Windows Issue
description: Create a report for an issue on Windows
labels: ["windows"]
type: Bug
body:
- type: textarea
  id: description
  attributes:
      label: Description of the issue
      description: >
          If possible, try an [MPC-QT development build](https://mpc-qt.github.io/downloads#dev-builds)
          to make sure the issue hasn't been fixed yet.


          Please provide the following information if applicable, remove unneeded lines:
      value: |
          - MPC-QT version: (shown in the menu Help > About This Program)
          - Window Version: Windows 10 / Windows 11...
          - GPU Make: AMD / Intel / Nvidia
          - Latest known working version: 
          - Issue started after the following happened: 

          # Description of the issue

          (remove this line and describe your issue here)
      render: text
  validations:
      required: true



